name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@main

      - name: Setup node env 🏗
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-online --no-audit

      - name: Run linter 👀
        run: npm run lint
